languageCode = "en"
languageName = "English"
weight = 1
title = "Aldar Ali - System Engineer and Cybersecurity enthusiast"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/logo.png"
  logoAlt = "Aldar Ali - System Engineer and Cybersecurity enthusiast"
  #secondaryLogo = ""
  description = "System Engineer and cybersecurity enthusiast with a focus on penetration testing, network security, and data protection."
  keywords = ["Aldar Ali", "cybersecurity", "penetration testing", "System Engineer", "network security", "data protection"]