# -- Markup --
# These settings are required for the theme to function.

[goldmark]
[goldmark.renderer]
  unsafe = true

[highlight]
  noClasses = false
  codeFences = true
  guessSyntax = false
  lineNos = false
  lineNumbersInTable = false

[tableOfContents]
  startLevel = 1
  endLevel = 6