# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.

colorScheme = "avocado"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true

mainSections = ["posts"]
# robots = ""

disableImageOptimization = true
disableTextInHeader = true

# Add default image for social media and search engines
defaultImage = "/img/logo.png"
#defaultFeaturedImage = ""
defaultBackgroundImage = "/img/technologybackground.jpg"
defaultBackgroundImageAlt = "Technology background image"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

[header]
  layout = "fixed"

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true
  
# Disable image zoom to reduce JS in HTML
disableImageZoom = true

[homepage]
  layout = "background" # valid options: page, profile, custom
  homepageImage = "img/technologybackground.jpg"
  homepageImageAlt = "Technology background image"
  showRecent = true
  showRecentItems = 12
  showMoreLink = true
  showMoreLinkDest = '/posts'
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateOnlyInArticle = true
  showDateUpdated = false
  showAuthor = true
  showHero = true
  heroStyle = "background" # changed from "background" to "basic" for simpler rendering
  layoutBackgroundBlur = true # disable blur for performance
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  editURL = ""
  editAppendPath = true
  seriesOpened = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = false
  showTableOfContents = true
  showRelatedContent = true # disable related content to reduce HTML size
  relatedContentLimit = 3 # reduced from 6
  showTaxonomies = true 
  showAuthorsBadges = true
  showWordCount = false
  showSummary = true
  sharingLinks = [ "linkedin", "twitter", "email"] # reduced sharing links

[list]
  showHero = true
  heroStyle = "background"  # changed from "background" to "basic"
  layoutBackgroundBlur = true  # disabled blur for performance
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showSummary = false
  showTableOfContents = false
  showCards = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background"  # changed from "background" to "basic"
  showBreadcrumbs = false
  showViews = false  # disabled views count to reduce JS
  showLikes = false  # disabled likes to reduce JS
  showTableOfContents = true  # disabled TOC for simpler pages

[term]
  showHero = true
  heroStyle = "background"  # changed from "background" to "basic"
  showBreadcrumbs = false
  showViews = false  # disabled views count to reduce JS
  showLikes = false  # disabled likes to reduce JS
  showTableOfContents = true  # disabled TOC for simpler pages
  groupByYear = false
  cardViewScreenWidth = false
  cardView = false

[buymeacoffee]
  identifier = "aldarali"
  globalWidget = true
  globalWidgetMessage = ""
  globalWidgetColor = "#FFDD00"
  globalWidgetPosition = "Right"
