# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.

colorScheme = "blowfish"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true

mainSections = ["posts"]
# robots = ""

disableImageOptimization = false
disableTextInHeader = true

# Add default image for social media and search engines
defaultImage = "/img/logo.png"
#defaultFeaturedImage = ""
defaultBackgroundImage = "/img/wallhaven.png"
defaultBackgroundImageAlt = "background image"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

[header]
  layout = "fixed"

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true
  
# Disable image zoom to reduce JS in HTML
disableImageZoom = true

[homepage]
  layout = "background" # valid options: page, profile, custom
  homepageImage = "img/wallhaven.png"
  homepageImageAlt = "background image"
  showRecent = true
  showRecentItems = 9
  showMoreLink = true
  showMoreLinkDest = '/posts'
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateOnlyInArticle = true
  showDateUpdated = false
  showAuthor = true
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true 
  showDraftLabel = true
  showEdit = false
  editURL = ""
  editAppendPath = true
  seriesOpened = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = false
  showTableOfContents = true
  showRelatedContent = true 
  relatedContentLimit = 3
  showTaxonomies = true 
  showAuthorsBadges = true
  showWordCount = false
  showSummary = true
  sharingLinks = [ "linkedin", "twitter", "email"] # reduced sharing links

[list]
  showHero = true
  heroStyle = "background" 
  layoutBackgroundBlur = true 
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showSummary = false
  showTableOfContents = false
  showCards = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background" 
  showBreadcrumbs = false
  showViews = false  
  showLikes = false  
  showTableOfContents = true

[term]
  showHero = true
  heroStyle = "background"  
  showBreadcrumbs = false
  showViews = true
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardViewScreenWidth = false
  cardView = false

[buymeacoffee]
  identifier = "aldarali"
  globalWidget = true
  globalWidgetMessage = ""
  globalWidgetColor = "#FFDD00"
  globalWidgetPosition = "Right"
